baseURL = "https://graalvmonlambda.com"
title = "GraalVM on Lambda"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]

  # (Optional, default none) Set source repository location. Used for 'Edit this page' links.
  # You can also specify this parameter per page in front matter.
  geekdocRepo = "https://github.com/marksailes/graalvm-on-lambda"

  # (Optional, default none) Enable 'Edit this page' links. Requires 'GeekdocRepo' param
  # and path must point to 'content' directory of repo.
  # You can also specify this parameter per page in front matter.
  geekdocEditPath = "edit/main/quickstart/content"